# Generated by Django 4.1.3 on 2022-12-11 14:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_dogprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('dest', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('dog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='world.dogprofile')),
            ],
        ),
    ]
