# Generated by Django 4.1.3 on 2022-12-11 15:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_walkroutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogprofile',
            name='dest',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='dogprofile',
            name='start',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.DeleteModel(
            name='WalkRoutes',
        ),
    ]
